config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'
  devise_for :users

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        @total = params[:total].to_d
        @session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          line_items: [
            {
              price_data: {
                currency: 'eur',
                unit_amount: (@total*100).to_i,
                product_data: {
                  name: 'Rails Stripe Checkout',
                },
              },
              quantity: 1
            },
          ],
          mode: 'payment',
          success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
          cancel_url: checkout_cancel_url
        )
        redirect_to @session.url, allow_other_host: true
    end
    
    def success
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
    
    def cancel
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> 
<h1>Echec</h1> 
<p>Le paiement n'a pas abouti.</p> 
</div>

app/views/checkout/success.html.erb
<html>
    <body>    
        <div class="container text-center my-5"> 
            <h1>Succès</h1> 
            <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p> 
            <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> 
        </div>
    </body>
</html>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
    <div class="madiv">
        <p style="color: green"><%= notice %></p>
        <h1>Events</h1>
    </div>
    <div class="container">
        <% @events.each do |event| %>
          <div class="card">
            <div class="card-body">
              <div id="events">
                <%= render event %>
                <p>
                <%= link_to "Show this event", event %>
                </p>
              </div>
            </div>
          </div>
      <% end %>
    </div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    margin: 80px auto;
  }

  #events {
      color: white;
  }

  .card {
    background: rgb(70,0,139);
    background: linear-gradient(114deg, rgba(70,0,139,1) 0%, rgba(6,0,203,1) 0%);
    width: 300px;
    margin: 10px;
  }

  .card-body {
    padding: 10px;
  }

  .madiv {
    text-align: center;
    margin-bottom: 20px;
  }

app/views/events/new.html.erb
    <div class="container">
      <h1>New event</h1>
        <%= render "form", event: @event %>
      <br>
      <div>
      <%= link_to "Back to events", events_path %>
      </div>
    </div>

<style>
.container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin: 80px auto;
}
</style>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= button_to "Passer commande", checkout_create_path(total: Event.find(params[:id]).price), class: "btn btn-primary", data: {turbo: false} %>
  <%= link_to "Edit this event", edit_event_path(@event) %> 
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="foot-container">
        <ul class="social-links">
            <li><a href="http://www.twitter.com"><i class="fab fa-twitter"></i></a></li>
            <li><a href="http://www.instagram.com"><i class="fab fa-instagram"></i></a></li>
            <li><a href="http://www.tiktok.com"><i class="fab fa-tiktok"></i></a></li>
        </ul>
        <p>&copy;Rochaya 2023. Tous droits réservés.</p>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="nav">
    <%= link_to(root_path, class: "home-link") do %>
      <h2>EventBrite</h2>
    <% end %>

    <div class="list-nav">
      <ul>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Créer ton event !", new_event_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Créer ton event !", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
            <%= link_to "Qui sommes-nous ?", '#' , class:"nav-link" %>
        </li>
      </ul>
    </div>

    <% if user_signed_in? %>
      <div class="dropdown">
        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil / Déconnexion
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Profil</a>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div class="dropdown">
        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Connexion / Inscription
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
          <a class="dropdown-item" href="<%= new_user_registration_path %>">Inscription</a>
        </div>
      </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://js.stripe.com/v3/"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="icon" href="https://cdn.discordapp.com/emojis/1094966135285370892.webp?size=96&quality=lossless" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header role="banner">
      <%= render 'layouts/navbar' %>
    </header>
    <main class="container-fluid py-5 my-3">
    <%= render "layouts/footer" %>
    <%= yield %>
    </main>

  </body>
</html>